[package]
name = "swcevaluator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_core = { version = "0.79", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_minifier",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

[dev-dependencies]
testing = "0.33"
swc_core = { version = "0.79", features = [
  "testing_transform",
  "ecma_parser",
] }
